### ISSUE TITLE
Create 'Facility' component

### ISSUE THREAD

**Issue by siqbal181** [Pensano-dev/aura-mobile-app#4]
By Attribute, I am referring to the qualities that can be selected on the first screen, e.g. quiet space, wifi, outdoor space, etc.
The first screen will map an array of these components.

![Image](https://github.com/Pensano-dev/aura-mobile-app/assets/19639889/5d905cb4-7ae1-4b80-bf23-e8a8127939e9)

https://excalidraw.com/#room=7616cae564c0125b181f,dKG9tVW08y1XNY1TEJGJOA

**Comment by siqbal181** [comment]
@pablisch Just to be clear - is an individual attribute a resuable part of the screen which should contain a logo/tooltil etc so it will represent one of these?



![Image](https://github.com/Pensano-dev/aura-mobile-app/assets/114309741/a62ff19e-3f86-49ed-8da4-338f70aa069c)

**Comment by pablisch** [comment]
Exactly that, except I don't know what tooltil is. We discussed that these attribute icons will also need text.

**Comment by pablisch** [comment]
Completed
