### ISSUE TITLE
🧪 test: home page (selection page)

### ISSUE THREAD

**Issue by junocchi** [Pensano-dev/aura-mobile-app#56]
Add component/unit tests to the selection page #55 

![Image](https://github.com/Pensano-dev/aura-mobile-app/assets/111089373/b10318d5-056f-4fbd-adb5-2ba795886c32)
![Image](https://github.com/Pensano-dev/aura-mobile-app/assets/111089373/4261eac4-db27-4626-adf3-00bccf5dcd47)

**Comment by pablisch** [comment]
Test will go in the same Epic ticket as the main code.
