### ISSUE TITLE
Consider what is needed for the mongoose Cafe model and create or feedback to group

### ISSUE THREAD

**Issue by junocchi** [Pensano-dev/aura-mobile-app#7]
What properties will be needed for the Cafe model, the database objects containing all the information about the cafes that we get data for, e.g. location, an array of attribute qualities, etc?

This could then be created for discussion or simply fed back to the group. This is likely to change as we work on the app so don't feel it has to be perfect first time.

**Comment by pablisch** [comment]
Completed.
