### ISSUE TITLE
Build out 10 lines of data on Supabase

### ISSUE THREAD

**Issue by tessconnell14** [Pensano-dev/aura-mobile-app#98]
Assign facilities to cafes so that when user selects a facility, 1-2 cafes are returned and shown on the cafe list

**Comment by Tian807** [comment]
I have added 10 lines of data on Supabase
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/dce7e42f-8be0-40ba-a449-2ff37d363a6d">
